application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      postmirror:
        license: Apache-2.0
        actions:
          reflect:
            function: actions/reflect/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          waaduser:
            function: actions/waaduser/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          waadpass:
            function: actions/waadpass/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          waadshutdown:
            function: actions/waadshutdown/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          imsuser:
            function: actions/imsuser/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          waaddisplay:
            function: actions/waaddisplay/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
